<?PHP
/* Examples for PHP-PDB library - Twister - HTML to common format filters
 *
 * Copyright (C) 2001 - PHP-PDB development team
 * Licensed under the GNU LGPL software license.
 * See the doc/LEGAL file for more information
 * See http://php-pdb.sourceforge.net/ for more information about the library
 */

function FilterHTML($fileData) {
   ShowError('HTML Filters do not work yet.');
   return false;
}